site_name: DemandCast
theme:
  name: material
  icon:
    logo: octicons/zap-24
    repo: octicons/git-branch-24
  favicon: lightning_logo.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.integrate

plugins:
  - privacy
  - search

repo_name: OET/demandcast
repo_url: https://github.com/open-energy-transition/demandcast

nav:
  - index.md
  - ETL/ETL.md
  - Models:
      - Models/index.md
      - Models/xgboost.md
  - Deployment/index.md
