# -*- coding: utf-8 -*-
"""
License: AGPL-3.0

Description:

    This script generates a map of the countries and subdivisions with available data.

    The shapes of standard countries and subdivisions are taken from the Natural Earth database.

    The shapes of non-standard countries and subdivisions are taken from the shapes generated by the respective scripts.
"""

import os

import cartopy.crs
import cartopy.feature
import matplotlib.pyplot
import util.directories
import util.shapes
import util.entities

# Create a directory to store the figures.
figure_directory = util.directories.read_folders_structure()["figures_folder"]
os.makedirs(figure_directory, exist_ok=True)

# Read the codes of all countries and subdivisions.
codes = util.entities.read_all_codes()

# Define the map projection and the coordinate reference system of the data to plot.
map_projection = cartopy.crs.Robinson(central_longitude=0)
data_crs = cartopy.crs.PlateCarree()

# Initialize the figure.
fig, ax = matplotlib.pyplot.subplots(
    figsize=(12, 16), subplot_kw={"projection": map_projection}
)

# Plot the land.
ax.add_feature(cartopy.feature.LAND, facecolor="lightgray")

# Loop over the countries.
for code in codes:
    # Get the shape of the country or subdivision.
    entity_shape = util.shapes.get_entity_shape(code, make_plot=False)

    # Plot the country or subdivision.
    entity_shape.plot(
        ax=ax,
        transform=data_crs,
        facecolor="tomato",
        edgecolor="black",
        linewidth=0.5,
        aspect=None,
        autolim=False,
    )

# Add title.
ax.set_title(
    "Countries and subdivisions with available data", fontsize=20, y=1.05, weight="bold"
)

# Save the figure.
fig.savefig(
    os.path.join(figure_directory, "available_entities.png"),
    dpi=600,
    bbox_inches="tight",
)
