name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint:
    timeout-minutes: 10
    name: "lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - uses: pre-commit/action@v3.0.1

  pytest:
    timeout-minutes: 10
    name: "pytest-${{ matrix.component }}"
    strategy:
      matrix:
        include:
          - component: ETL
            working-directory: ./ETL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: "Install uv"
        uses: astral-sh/setup-uv@v5

      - name: "Pytest run tests"
        run: uv run pytest
        working-directory: ${{ matrix.working-directory }}

      - name: "Pytest check coverage report"
        run: uv run pytest --cov=utils --cov-report=term-missing --cov-fail-under=95
        working-directory: ${{ matrix.working-directory }}
